kind: Pod
apiVersion: v1
metadata: 
        name: tcspod2
spec: 
        containers: 
                - name: c00
                  image: nginx
                  ports: 
                        - containerPort: 80


