kind: Deployment
apiVersion: apps/v1
metadata: 
        name: httpddeployment1

spec: 
        replicas: 3
        selector:
                matchLabels:
                        name: deployment2
        template:
                metadata:
                        name: revpod
                        labels:
                                name: deployment2
                              
                spec:
                        containers:
                                - name: c00
                                  image: httpd
                                  ports:
                                        - containerPort: 80




