kind: Service
apiVersion: v1
metadata:
        name: demoservice-nodeport

spec: 
        ports:
                - port: 80
                  targetPort: 80
        selector:
                name: deployment2
        type: NodePort
