kind: ReplicaSet
apiVersion: apps/v1
metadata: 
        name: myreplica

spec: 
        replicas: 2
        selector:
                matchLabels: 
                         myname: ankit
        template: 
                metadata:
                        name: testpod
                        labels: 
                                myname: ankit
                spec: 
                        containers: 
                                - name: c00
                                  image: ubuntu
                                  command: ["/bin/bash", "-c", "while true; do echo TCS; sleep 5s ; done"]

