kind: Pod
apiVersion: v1
metadata: 
        name: volsecret
spec:
        containers:
                - name: c00
                  image: ubuntu
                  command: ["bin/bash", "-c", "while true; do echo Hi Ankit;sleep 5s; done"]
                  volumeMounts: 
                        - name: xchange
                          mountPath: "/tmp/secrets"


        volumes:
                - name: xchange
                  secret:
                          secretName: mysecret






    
